version: "3.8"

services:
  database:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    environment:
      - DB_HOST=127.0.0.1
    volumes:
      - ./:/app
    network_mode: host
    # Don't run as root, so that generated files have the correct user
    user: ${UID:-1000}:${GID:-1000}
